server {
  listen 80;
  server_name _;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  location /ollama/ {
    proxy_pass http://ollama:11434/;
  }

  location /openwebui/ {
    proxy_pass http://openwebui:8080/;
  }

  location /browser-use/ {
    proxy_pass http://browser-use-webui:7788/;
  }

  location /vnc/ {
    proxy_pass http://browser-use-webui:6080/;
  }
}
