server {
  listen 80;
  server_name _;

  resolver 127.0.0.11 valid=30s ipv6=off;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  location /ollama/ {
    proxy_pass http://ollama:11434/;
  }

  location /openwebui/ {
    proxy_pass http://open-webui:8080/;
    proxy_set_header Host $host;
  }

  location /browser-use/ {
    proxy_pass http://host.docker.internal:7788/;
    proxy_set_header Host $host;
  }

  location /vnc/ {
    proxy_pass http://host.docker.internal:6080/;
    proxy_set_header Host $host;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
